### ISSUE TITLE
Add ability to save to yaml

### ISSUE THREAD

**Issue by mdxprograms** [18F/jekyll-get#14]
It would be nice to add a preference to set a flag for saving to yaml or json.
This would be mainly beneficial if using the `cache` setting.

```
jekyll_get:
  - data: apod
    url: https://api.nasa.gov/planetary/apod?api_key=NNKOjkoul8n1CH18TWA9gwngW1s1SmjESPjNoUFo
    type: yaml
    cache: true
```
